### ISSUE TITLE
ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.

### ISSUE THREAD

**Issue by Animacrep** [jazzband/django-avatar#222]
ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.

Can you give a suggestion for this? it always error

**Comment by Animacrep** [comment]
I found

atching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\WINDOWS10\Downloads\simple-django-login-and-register-dynamic-lang-main\simple-django-login-and-register-dynamic-lang-main\source\env\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "c:\Users\WINDOWS10\Downloads\simple-django-login-and-register-dynamic-lang-main\simple-django-login-and-register-dynamic-lang-main\source\env\lib\site-packages\django\core\management\commands\runserver.py", line 125, in inner_run
    autoreload.raise_last_exception()
  File "c:\Users\WINDOWS10\Downloads\simple-django-login-and-register-dynamic-lang-main\simple-django-login-and-register-dynamic-lang-main\source\env\lib\site-packages\django\utils\autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "c:\Users\WINDOWS10\Downloads\simple-django-login-and-register-dynamic-lang-main\simple-django-login-and-register-dynamic-lang-main\source\env\lib\site-packages\django\core\management\__init__.py", line 398, in execute
    autoreload.check_errors(django.setup)()
  File "c:\Users\WINDOWS10\Downloads\simple-django-login-and-register-dynamic-lang-main\simple-django-login-and-register-dynamic-lang-main\source\env\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "c:\Users\WINDOWS10\Downloads\simple-django-login-and-register-dynamic-lang-main\simple-django-login-and-register-dynamic-lang-main\source\env\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "c:\Users\WINDOWS10\Downloads\simple-django-login-and-register-dynamic-lang-main\simple-django-login-and-register-dynamic-lang-main\source\env\lib\site-packages\django\apps\registry.py", line 116, in populate
    app_config.import_models()
  File "c:\Users\WINDOWS10\Downloads\simple-django-login-and-register-dynamic-lang-main\simple-django-login-and-register-dynamic-lang-main\source\env\lib\site-packages\django\apps\config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Program Files\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "c:\Users\WINDOWS10\Downloads\simple-django-login-and-register-dynamic-lang-main\simple-django-login-and-register-dynamic-lang-main\source\env\lib\site-packages\avatar\models.py", line 17, in <module>
    from avatar.conf import settings
  File "c:\Users\WINDOWS10\Downloads\simple-django-login-and-register-dynamic-lang-main\simple-django-login-and-register-dynamic-lang-main\source\env\lib\site-packages\avatar\conf.py", line 6, in <module>
    class AvatarConf(AppConf):
  File "c:\Users\WINDOWS10\Downloads\simple-django-login-and-register-dynamic-lang-main\simple-django-login-and-register-dynamic-lang-main\source\env\lib\site-packages\avatar\conf.py", line 8, in AvatarConf
    RESIZE_METHOD = Image.ANTIALIAS
  File "c:\Users\WINDOWS10\Downloads\simple-django-login-and-register-dynamic-lang-main\simple-django-login-and-register-dynamic-lang-main\source\env\lib\site-packages\PIL\Image.py", line 70, in __getattr__
    deprecate(name, 10, f"Resampling.{old_resampling[name]}")
  File "c:\Users\WINDOWS10\Downloads\simple-django-login-and-register-dynamic-lang-main\simple-django-login-and-register-dynamic-lang-main\source\env\lib\site-packages\PIL\_deprecate.py", line 62, in deprecate
    warnings.warn(
DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead

**Comment by CarrotManMatt** [comment]
I'm getting this as well! Ithink it's more of a warning because it is not depreciated yet (but will be soon!)

One hacky way around it is to create a local python file that imports everything from django-avatar, then overrides the code that is causing this issue. Then throughout your project use your local version of the package. Alternatively, wait for this to be fixed in the official package.

**Comment by 0xMRTT** [comment]
#226 fixed that
